version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-local
    container_name: helpcar-customer
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local-docker
      DB_USER: helpcar-customer-local
      DB_PASSWORD: helpcar-customer-local

  db:
    image: postgres
    environment:
      POSTGRES_USER: helpcar-customer-local
      POSTGRES_PASSWORD: helpcar-customer-local
    ports:
      - "5432:5432"