version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-local
    container_name: helpcar-customer
    depends_on:
      - db
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: local
      PORT: 8082

  db:
    image: postgres
    environment:
      POSTGRES_USER: hepcar-customer-local
      POSTGRES_PASSWORD: root
      ports: "5436:5436"