#Spring Properties
spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/hepcar-customer-local?schema=helpcar_customer
    username: helpcar-customer-local
    password: helpcar-customer-local