#Server Properties
server:
  port: 8083

#Spring Properties
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

#Prometheus
management:
  server:
    port: 8081
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info"
          - "metrics"
          - "actuator"
  metrics:
    export:
      prometheus:
        enabled: true